### ISSUE TITLE
Talk Topics

### ISSUE THREAD

**Issue by djdefi** [NevadaCountyFreeCodeCamp/meetup#11]
List of potential interesting talks:

## Software Development 

- [ ] HTML & CSS Basics / Intro - @jkinley / group ?
- [x] GitHub / Version Control - @djdefi
- [ ] [Open Source Friday](https://opensource.guide/how-to-contribute/) (Contributing to Open Source Software) - @djdefi
- [ ] Intro to "DevOps" and CI / CD workflows - @djdefi
- [ ] Intro to React 

## Cloud 

- [ ] Intro to Amazon Web Services (EC2, Route53, S3, RDS) - @djdefi
- [ ] Cloud based DevOps (Using Ansible, chef, Terraform etc to manage AWS resources)

## Security

- [ ] Everyday security (Ad-blocking, HTTPS everywhere, VPN, privacy)
- [ ] Hosting secure applications (Web server hardening, configuration, HTTPS, LetsEncrypt) - @djdefi
- [ ] Intro to Cloudflare / CDN - @djdefi 

## Careers 

- [ ] Beginner -> Job candidate pathways

**Comment by GerrittDorland** [comment]
I think starting with a Git tutorial would be a great starting place. Source control is becoming a major essential that a lot of schools/companies assume you know going in... It'd be handy for new people - especially when it comes to contributing here. Plus, it'd be a good refresher for those of us stuck in SVN or Merc. land.
