### ISSUE TITLE
Code Examples?

### ISSUE THREAD

**Issue by GerrittDorland** [NevadaCountyFreeCodeCamp/meetup#12]
It might be cool to push some of our personal projects on here to populate the repo a bit. Maybe it could lead to explanatory code reviews to teach both the project creator what they could do better, and expose newer folks to how the average joe stumbles through code...

Would it be appropriate to add some of our personal projects to the repo?

I have a Markov Chain I could add.

**Comment by andreas-groos** [comment]
I would like that. Seems useful and informative for both sides. I'll make a repo available in the next days.

**Comment by djdefi** [comment]
I would prefer to keep this `meetup` repo focused on the Meetup internals and planning etc. We can create as may repos as we want under the https://github.com/NevadaCountyFreeCodeCamp organization, so I would prefer to separate out different areas of interest / responsibility. We can always link to other repos or use submodules etc them in whatever landing page format we want. 

I had two ideas for how it could look:

1. A separate `showcases` or `projects` repo under https://github.com/NevadaCountyFreeCodeCamp with folders for each camper or organized by language / concept etc.

2. Keep projects in personal repos, but have a sort of "showcase" or portfolio on our camper profiles on the webpage https://github.com/NevadaCountyFreeCodeCamp/nevadacountyfreecodecamp.github.io/issues/6 - If the projects are the subject of a ⚡️ talk then they could also be linked to from the talks page on the site.

**Comment by smspierings** [comment]
I missed so much on this....would like a quick rundown of how to contribute etc. Anyone have some time in the next week or so? Otherwise I'll wait till next Meetup and ask then...thanks!

**Comment by andreas-groos** [comment]
Did you have a look at [https://github.com/NevadaCountyFreeCodeCamp/nevadacountyfreecodecamp.github.io](url)?
If you are comfortable adding content/new features just go ahead, write the code and do a pull request. That's the only project we have going at this point to contribute. For other questions write me at andreas-groos on gitter
