### ISSUE TITLE
Logo & Banner graphics

### ISSUE THREAD

**Issue by djdefi** [NevadaCountyFreeCodeCamp/meetup#2]
It would be cool if we had our own logo and banner!

**Comment by andreas-groos** [comment]
What dimensions/size you would want for the banner?

**Comment by djdefi** [comment]
That is a great question! I really have no idea what is best for the banner. I suppose that would somewhat depend on what layout we want for #4 

For an icon, something that is a `.svg` would be cool so it looks good everywhere. Not sure if `.svg` can also be used in banners (my lack of web design skills are showing 😄 ).
